# Generated by Django 4.1.3 on 2022-11-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='data',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
